import './global.css';
import { UiLayout } from '@/components/ui/ui-layout';
import { ClusterProvider } from '@/components/cluster/cluster-data-access';
import { SolanaProvider } from '@/components/solana/solana-provider';
import { ReactQueryProvider } from './react-query-provider';
import Script from 'next/script';

export const metadata = {
  title: 'mint-ware',
  description: 'Generated by create-solana-dapp',
};

const links: { label: string; path: string, dev? : boolean }[] = [
  { label: 'List Your Token 🚀', path: '/' },
  ... (process.env.NEXT_PUBLIC_NODE_ENV ?? process.env.NODE_ENV) == 'development' ? [
  { label: 'Leaderboard 📈', path: '/leaderboard', dev: true },
  { label: 'Team Dashboard 🎯', path: '/team-dashboard', dev: true },
  { label: 'Buy $MWT 💰', path: '/mint-ware', dev: true },
  ] : [],
];


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <head>
      <Script async src="https://terminal.jup.ag/main-v3.js" data-preload />
      </head>
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <UiLayout links={links}>{children}</UiLayout>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
